### PR TITLE
fix error in pairwise_generator function

### PR DESCRIPTION
**Pull request by nikitajz**
there should be `input_data` instead of `data` in for loop in `pairwise_generator` function

### CODE REVIEW

**Comment by nikitajz** [comment]
@stripathi08 can you take a look at this one please?

**Comment by stripathi08** [comment]
@nikitajz Thanks for pointing it out. Will make the changes in the next push.

**Comment by rbrigden** [comment]
Can we just merge this in?

**Comment by stripathi08** [comment]
We can. I was being cautious to avoid errors in the master branch. I have merged it now.

**Pull request merged**
